### ISSUE TITLE
Unable to define arc4() call address...

### ISSUE THREAD

**Issue by lkddi** [yanncam/UnSHc#10]
Unable to define arc4() call address...

centos
 Linux version 2.6.32-573.22.1.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) ) #1 SMP Wed Mar 23 03:35:39 UTC 2016
Linux iZ2zejdh2ap4dldv31rd38Z 2.6.32-573.22.1.el6.x86_64 #1 SMP Wed Mar 23 03:35:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

[ssr.txt](https://github.com/yanncam/UnSHc/files/531270/ssr.txt)

**Comment by yanncam** [comment]
Hello,

As describe in the README.md of this repository :

I will not decrypt any file for people. Issues on GitHub are only to discuss about bug and/or improvement of the tool "UnSHc".

If you think you have found a bug, please provide me the encrypted file **AND the unencrypted file** corresponding. Without these two files I can't reverse it and analyze it. Add some information about the architecture where the encrypted file has been created (what linux distribution and version, what architecture x86 or x64, etc.).

**All others "file decryption issues" will be closed directly.**

Plus, concerning your file ssr.txt provided in attachement, it doesn't seem to be encrypted by SHc, so UnSHc is useless for this case. If you open your file via a simple text editor, you can see this in plaintext :

> ENcode BY XGADML powered BY XUAN 2016-09-27Copyright (C) 2016-2019 the XGADmlam.

Some URLs are present too.

Sincerely,

**Comment by jatinnijash** [comment]
_   _       _____ _   _      
| | | |     /  ___| | | |     
| | | |_ __ \ `--.| |_| | ___ 
| | | | '_ \ `--. \  _  |/ __|
| |_| | | | /\__/ / | | | (__ 
 \___/|_| |_\____/\_| |_/\___|

--- UnSHc - The shc decrypter.
--- Version: 0.8
------------------------------
UnSHc is used to decrypt script encrypted with SHc
Original idea from Luiz Octavio Duarte (LOD)
Updated and modernized by Yann CAM
- SHc   : [http://www.datsi.fi.upm.es/~frosal/]
- UnSHc : [https://www.asafety.fr/unshc-the-shc-decrypter/]
------------------------------

[*] Input file name to decrypt [Direct.sh.x]
/usr/bin/objdump: can't disassemble for architecture UNKNOWN!

[-] Unable to define arc4() call address...

**Comment by jatinnijash** [comment]
any help please

**Comment by jatinnijash** [comment]
i am used ubuntu  Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-31-generic i686)

**Comment by edson78** [comment]
@lkddi 
do this:

Install gcc lib packages.

It resolved my problem.

I hope'd to help.

**Comment by heroes1412** [comment]
> @lkddi do this:
> 
> Install gcc lib packages.
> 
> It resolved my problem.
> 
> I hope'd to help.

which lib bro?
