### ISSUE TITLE
Having issue using UnSHc

### ISSUE THREAD

**Issue by NicholasLAranda** [yanncam/UnSHc#11]
https://transfer.sh/hC8Zy/postinst

I am running a competition with some friends and they insist that it's possible to encrypt a postinst file for a jailbroken iOS debian package, which we've been discussing that it's just not possible for many various reasons.

They finally provided a sample file and in the process of me trying to obtain the source code, I came across your tool to un-shc scripts: exactly what I need to prove them wrong ahah

Anyways, when I run unshc I get this:

`[*] Input file name to decrypt [postinst]
BFD: unable to read unknown load command 0x21
BFD: unable to read unknown load command 0x29
/sw/bin/objdump: can't disassemble for architecture UNKNOWN!

BFD: unable to read unknown load command 0x21
BFD: unable to read unknown load command 0x29
[-] Unable to define arc4() call address...`

Am I missing more /bin files? I've already had to obtain shc and objtools for objdump, is BFD another bin I need, or am I missing something else here?

The file I uploaded I think I've only ran chmod 777 on it, so IDK if that will effect it. I have no idea what the source file was compiled on, but most likely it was compiled under an intel based mac since most jailbreak developers use that environment for ease of use.

The target device is a 64 bit iPhone 6+ and I don't remember off the top of my head what type of ARM artecture it uses, but it's definitely compatible with 32/64 bit.

**Comment by yanncam** [comment]
Hello RypeDub40,

UnSHc is a tool to decrypt only SHc's encrypted file.
Plus, UnSHc has some limits based on compilation architecture sadly.

UnSHc was tested successfully on :

**Ubuntu 14.04.3 LTS x86_64**
- Linux server 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- Linux version 3.13.0-61-generic (buildd@lgw01-50) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015

**CentOS release 6.6 (Final) x86_64**
- Linux server 2.6.32-504.23.4.el6.x86_64 #1 SMP Tue Jun 9 20:57:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- Linux version 2.6.32-504.23.4.el6.x86_64 (mockbuild@c6b9.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) ) #1 SMP Tue Jun 9 20:57:37 UTC 2015

**Debian 7.8 i686**
- Linux server 3.2.0-4-686-pae #1 SMP Debian 3.2.68-1+deb7u2 i686 GNU/Linux
- Linux version 3.2.0-4-686-pae (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-14) ) #1 SMP Debian 3.2.68-1+deb7u2

Only x86/x64 architecture are supported. The tool doesn't support ARM-based architecture (it's in project, if you want to contribute, don't hesitate ;)).

I have never tried SHc/UnSHc on an iOS equipment and it's not supported at this time.

Sincerely,
