### ISSUE TITLE
ARM64 Can not run.

### ISSUE THREAD

**Issue by Shell-mirrors** [yanncam/UnSHc#15]
When I run unshc [filename] prompt: Unable to define arc4 () call address ...
I am running on Ubuntu xenial ARM64.
Hope to support the arm architecture. . .

**Comment by yanncam** [comment]
Hello,

Yes, indeed, as it said on the README.md, ARM architecture aren't supported.

Sorry but it's on the todo list (without any deadline).

Sincerely,
