### ISSUE TITLE
PLEASE HELP ME I GOT THIS ERROR

### ISSUE THREAD

**Issue by hajimxmiku** [yanncam/UnSHc#16]
I tried to decrypt this bash file which is encrypted 
![screenshot_20180116-061830](https://user-images.githubusercontent.com/22914300/34963785-4fbefbfa-fa85-11e7-81f7-87066de328ae.png)

This is what I see in the bash file
![screenshot_20180116-061923](https://user-images.githubusercontent.com/22914300/34963803-64230050-fa85-11e7-93d1-db09ad0e283d.png)

**Comment by yanncam** [comment]
Hello,

As I understand, the system where you run UnSHc doesn't have the **objdump** binary. Install it before using UnSHc.
The **objdump** command (with the **-s** and **-D** arguments used by UnSHc) is a command on the system that is mandatory for UnSHc to work.

Sincerely,
