### ISSUE TITLE
Error on debian and centos6 unshc.sh: line 713: /tmp/ALoyWM: Permission denied

### ISSUE THREAD

**Issue by BigBWolfy** [yanncam/UnSHc#17]
I`ve got an issue with script.Tried it on centOS6 but had the same issue, decided to install Debian 7, but got the same issue.

![screenshot_2](https://user-images.githubusercontent.com/39609604/40524170-b82bfdfc-5fe1-11e8-8b16-51dcb55ec25b.png)
i already changed rights to 777 in tmp and shc 
the file i`m trying to decript:
[auto-script.sh.zip](https://github.com/yanncam/UnSHc/files/2037832/auto-script.sh.zip)

**Comment by yanncam** [comment]
Hello,

I think you have a security mecanism to prevent execution of script from the `/tmp` directory.
I have tried to decrypt your file from a **Kali Linux** with the latest UnSHc version and it works fine.

Do you want the decrypted version? I can upload it.

Sincerely,

**Comment by BigBWolfy** [comment]
Sure, thank you so munch :)

**Comment by yanncam** [comment]
[auto-script.zip](https://github.com/yanncam/UnSHc/files/2038796/auto-script.zip)

Be carefull, it seems to be an **HackTool** from Russia to compromise and persist on the server...

Have a nice day,

**Comment by BigBWolfy** [comment]
Its a tool to make from any VDS-smtp mail sender for AMS, you actually saved my day.Thank you for making this script and good luck to you.

**Comment by yanncam** [comment]
No problem :) !

I close the ticket,

**Comment by droidamlogic** [comment]
Hai yanncam,
Can you help me descrypt my file #

**Comment by rkanani108** [comment]
Hi @yanncam ,

We are facing challenges to decrypt the attached files. 
Could you please help us for this?

[files.zip](https://github.com/yanncam/UnSHc/files/7290953/files.zip)

Thanks
