### ISSUE TITLE
problem with raspberry pi

### ISSUE THREAD

**Issue by bedamusa** [yanncam/UnSHc#18]
./unshc.sh: line 9: syntax error near unexpected token `newline'
./unshc.sh: line 9: `<!DOCTYPE html>'

**Comment by yanncam** [comment]
Hello @bedamusa,

As describe on the README.md of UnSHc, this tool works only with x86 / x64 architecture. At the moment ARM (Raspberry Pi) isn't supported.

Sincerely,
