### ISSUE TITLE
？

### ISSUE THREAD

**Issue by mohan2096** [yanncam/UnSHc#2]
[_] Extracting password...
    [+] PWD address found : [0x611544]
    [+] PWD size found : [0x100]
[*] Executing [/tmp/iiqYfI] to decrypt [vpn7.sh.x]
[*] Retrieving initial source code in [vpn7.sh]
./unsh.sh: line 698: /tmp/iiqYfI: Permission denied
[_] All done!

**Comment by yanncam** [comment]
Hello,

As describe in your previous issu, you need to install GCC compiler on your CentOS before using UnSHC.

See here :
- https://github.com/yanncam/UnSHc/issues/1

Sincerely,

**Comment by yanncam** [comment]
Solved here : https://github.com/yanncam/UnSHc/issues/1
