### ISSUE TITLE
Unable to decrypt - files attached

### ISSUE THREAD

**Issue by IvoryJam** [yanncam/UnSHc#23]
Version 0.8
Unable to define arc4() call address...

[test.sh.txt](https://github.com/yanncam/UnSHc/files/3636897/test.sh.txt)
[test.sh.x.c.txt](https://github.com/yanncam/UnSHc/files/3636898/test.sh.x.c.txt)
[test.sh.x.txt](https://github.com/yanncam/UnSHc/files/3636899/test.sh.x.txt)

**Comment by yanncam** [comment]
Hello,

Which version of shc do you use ?
Please read : https://github.com/yanncam/UnSHc/issues/31

Sincerely,

**Comment by IvoryJam** [comment]
I was using 4.0.3-0.1, so it was the latest. Totally understand though! Good work still!

**Comment by yanncam** [comment]
I'll try to study the latest SHc version if I have free time :) !
Thanks a lot,
Have a nice day
