### ISSUE TITLE
Important Note

### ISSUE THREAD

**Issue by FOSSONLY** [yanncam/UnSHc#31]
Due to the many problems since shc 4.0.3, there seems to be a need for clarification. In shc 4.0.3 many structural changes have been incorporated, so that shc now makes use of various security mechanisms provided by the linux-kernel itself. Therefore, it is now almost impossible to extract the original shell script at all, if the new shc version was used. This requires a more in-depth approach, which means that a modified bash or a modified linux-kernel is needed to bypass the security measures. On the basis of a system with regular behaviour I don't see a big chance, even if there may be weaknesses in terms of security holes. At least in my own tests I was not able to extract the shell script without sabotaging the system.

**Comment by yanncam** [comment]
Hello @FOSSONLY,

Thank you for this clarification. I have not the free-time to deep into the new SHc version to update UnSHc for the moment...

I had your comment on the README to prevent future issue about incompatibility with UnSHc.

Sincerely,
