### ISSUE TITLE
Unable to define arc4() call address

### ISSUE THREAD

**Issue by SmartElec** [yanncam/UnSHc#34]
ubuntu18.04 amd64

`cat test.sh`
```
#!/bin/bash
echo "hello world"
```
`shc -f test.sh` #shc version 3.8.9b

```
$ unshc.sh test.sh.x -o dec.sh

[*] Input file name to decrypt [test.sh.x]
[+] Output file name specified [dec.sh]
[-] Unable to define arc4() call address...
```

**Comment by Ionnutz** [comment]
Same problem, I cannot even UnSHc the sample file, it must be some distro problem. Anyone any help?

**Comment by Coding-01** [comment]
> 的问题，我什至无法提供 UnSHc 示例文件，它一定是一些发行版问题。有人帮忙吗？
I also encountered the same problem. At first I thought there was a problem with the environment, but it was obviously wrong....
In /***/**/UnSHc/README.md it says: "I will not decrypt any file for people.
Issues on GitHub are only to discuss about bugs and/or improvement of the tool "UnSHc"."

**Comment by Coding-01** [comment]
> 的问题，我什至无法提供 UnSHc 示例文件，它一定是一些发行版问题。有人帮忙吗？
I also encountered the same problem. At first I thought there was a problem with the environment, but it was obviously wrong....
In /***/**/UnSHc/README.md it says: "I will not decrypt any file for people.
Issues on GitHub are only to discuss about bugs and/or improvement of the tool "UnSHc"."

**Comment by yanncam** [comment]
Hello,

When you use `shc` to protect a script, that script is only usable on the server where the shc's encryption has been done.

To make the encrypted script usable on multiple systems (generic), `shc` includes the `-r` argument to relax the security :

> -r Relax security. Make a redistributable binary

`UnSHc` works when the script has been encrypted with this option. 

Try with the encryption command:

```
./shc -v -r -f myScript.sh
```

Then the decryption command:

```
./unshc.sh myScript.sh.x
```

Sincerely,
