### ISSUE TITLE
There seems to be a problem.

### ISSUE THREAD

**Issue by mohan2096** [yanncam/UnSHc#5]
[*] Input file name to decrypt [kangml-ce7web]
[-] Unable to define arc4() call address...
decryption failure;
File address
https://transfer.sh/11r50u/ksf
And this 
https://transfer.sh/H0gme/zyzh
Sorry for the inconvenience

**Comment by yanncam** [comment]
Hello,

These binaries don't seems to be encrypted by SHc.
There is no "14 function calls" that can be identified in their object dumps.
My tools "UnSHc" can't revert these file.

I close the issue.

Sincerely,
