### ISSUE TITLE
Help, a new question, thank you！

### ISSUE THREAD

**Issue by mohan2096** [yanncam/UnSHc#6]
[root@VM_20_164_centos ~]# ./y cen 

```
_   _       _____ _   _      
| | | |     /  ___| | | |     
| | | |_ __ \ `--.| |_| | ___ 
| | | | '_ \ `--. \  _  |/ __|
| |_| | | | /\__/ / | | | (__ 
 \___/|_| |_\____/\_| |_/\___|

--- UnSHc - The shc decrypter.
--- Version: 0.7
------------------------------
UnSHc is used to decrypt script encrypted with SHc
Original idea from Luiz Octavio Duarte (LOD)
Updated and modernized by Yann CAM
- SHc   : [http://www.datsi.fi.upm.es/~frosal/]
- UnSHc : [https://www.asafety.fr/unshc-the-shc-decrypter/]
------------------------------

[*] Input file name to decrypt [cen]
[+] ARC4 address call candidate : [0x14c283e9]
[*] Extracting each args address and size for the 14 arc4() calls with address [0x14c283e9]...
[-] Unable to extract addresses of 14 arc4 args with ARC4 address call [0x14c283e9]...
[+] ARC4 address call candidate : [0x146175e1]
[*] Extracting each args address and size for the 14 arc4() calls with address [0x146175e1]...
[-] Unable to extract addresses of 14 arc4 args with ARC4 address call [0x146175e1]...
[-] Unable to define arc4() call address...
```

File address：https://transfer.sh/iIhUG/cen

**Comment by mohan2096** [comment]
@yanncam ？

**Comment by yanncam** [comment]
Can you send me the original *.sh file and the encrypted one, so I will compare the encryption between the two files and I'll analyze why this file isn't decrypted ?

**Comment by yanncam** [comment]
Hello,

**I will not decrypt any file for people.**
Issues on GitHub are only to discuss about bug and/or improvement of the tool "UnSHc".

If you think you have found a bug, please provide me the encrypted file **AND the unencrypted file corresponding**. Without these two files I can't reverse it and analyze it.
Add some information about the architecture where the encrypted file has been created (what linux distribution and version, what architecture x86 or x64, etc.).

All other "file decryption submission" will be closed directly.

Thank you in advance,

Sincerely,
