### ISSUE TITLE
a new question!

### ISSUE THREAD

**Issue by lala437** [yanncam/UnSHc#7]
- which: no gcc in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
-  _   _       _____ _   _  
- | | | |     /  ___| | | |  
- | | | |_ __ \ `--.| |_| | ___ 
- | | | | '_ \ `--. \  _  |/ __|
- | |_| | | | /__/ / | | | (__ 
## \- - [ ] |_/___|
- --- UnSHc - The shc decrypter.
- --- Version: 0.7
  - ------------------------------
- UnSHc is used to decrypt script encrypted with SHc
- Original idea from Luiz Octavio Duarte (LOD)
- Updated and modernized by Yann CAM
- \- SHc   : [http://www.datsi.fi.upm.es/~frosal/]
- \- UnSHc : [https://www.asafety.fr/unshc-the-shc-decrypter/]
  - ------------------------------
- 
- [*] Input file name to decrypt [main.sh.x]
- [-] Unable to define arc4() call address...

this file adress   https://drive.google.com/file/d/0B2oGSsjRZUOqdXI4NDd3b09lbGc/view?usp=sharing

thank you

**Comment by yanncam** [comment]
Hello,

**I will not decrypt any file for people.**
Issues on GitHub are only to discuss about bug and/or improvement of the tool "UnSHc".

If you think you have found a bug, please provide me the encrypted file **AND the unencrypted file corresponding**. Without these two files I can't reverse it and analyze it.
Add some information about the architecture where the encrypted file has been created (what linux distribution and version, what architecture x86 or x64, etc.).

All other "file decryption submission" will be closed directly.

Thank you in advance,

Sincerely,
