### ISSUE TITLE
how to decrypt this script？？

### ISSUE THREAD

**Issue by chenmin1992** [yanncam/UnSHc#8]
https://transfer.sh/mgg4t/hello.sh
the adress above is the script .

i have look over the same issue,but i can't still decrypt it.

this script has only one adress , but unshc can't  decrypt it.

the error is   Unable to extract addresses of 14 arc4 args with ARC4 address call [0x143b86b8]...

help me,please :)

**Comment by chenmin1992** [comment]
@yanncam

**Comment by yanncam** [comment]
Hello,

The script that you provide doesn't seem to be encrypted by SHc.
So my tool UnSHc isn't usefull for this one.

If you open your script in attachement, you will see the 43 lines at the begining that are not encrypted : it's pure SH/Bash script.
Then your script contains binary data (gzip format).

With a quick reading, I think your file contains shell script on top to auto-extract and uncompress binary data.

If you need to know what is the purpose of this script, extract and just uncompress (gzip) the binary data.

UnSHc isn't the right tool for this case.

BTW :
I will not decrypt any file for people. Issues on GitHub are only to discuss about bug and/or improvement of the tool "UnSHc".

If you think you have found a bug, please provide me the encrypted file AND the unencrypted file corresponding. Without these two files I can't reverse it and analyze it. Add some information about the architecture where the encrypted file has been created (what linux distribution and version, what architecture x86 or x64, etc.).

All others "file decryption issues" will be closed directly.

Sincerely,
