### ISSUE TITLE
非常不错

### ISSUE THREAD

**Issue by onesez** [yanncam/UnSHc#9]
火钳刘明

**Comment by yanncam** [comment]
Hello,

Please, write your issue in english.

Sincerely,

**Comment by Zaiakf** [comment]
Where script install for unshc?

**Comment by yanncam** [comment]
Hello,

You don't need an "install script", just use the "unshc.sh" file in a shell.

Sincerely,

**Comment by onesez** [comment]
英语我会说，但是你们会说中文么？

**Comment by yanncam** [comment]
Hello,

Please, write your issue in english...

Sincerely,

**Comment by onesez** [comment]
说中文,OK？Can you speak chiese?

**Comment by yanncam** [comment]
I dont' speak chinese. Only French or English.

**Comment by onesez** [comment]
你是法国人？
Are you French?

**Comment by onesez** [comment]
Come on, wo'men'ren'shi'yi.

**Comment by onesez** [comment]
Come on, we know.

**Comment by yanncam** [comment]
Yes.
Please referer to README.md for the "how to use UnSHc".
Sincerely,

**Comment by onesez** [comment]
About unshc I will use, I mean we can，OK？

**Comment by onesez** [comment]
I`m chinese.

**Comment by Zaiakf** [comment]
I dont understand, i type unshc.sh not found

**Comment by onesez** [comment]
This will not
